sudo: false
language: node_js
node_js:
  - "6"
  
addons:
  apt:
    packages:
      - gettext

before_script:
  - npm install -g grunt-cli

before_install:
  - chmod +x ./test/build_mo_files.sh
  - ./test/build_mo_files.sh

addons:
  sauce_connect: true

env:
  global:
    - secure: GRLxEem43P7BM1kVlu9fi9f5XVZFrTRmvU14Ams/Y8ECMx+WZweYYYmZgJZ10dfMun/KOQgx9BPUwuK0D69I3Iw/h2PrWxrpDrFKlTeSS4EmeUx3XfmLkiNEH1BXZ1n4Mq+mx6drFug5wLW2/0pCK2B0GcE5zgVMWpcm4mPgZ7w=
    - secure: DAA7sn/qWeHG/2SkYwvyxa9cz7zlNXwGA5aRXK37ZhVcxjQAD/Nzc0arRkyJC1r9UDIQYY9UrrhDvXcDz4aTxxQTQT4DYGnUpSzkdiyghRv1EQVJupgoLqGYX98zq2ycnhhtuh5+sxtY3x4bmaBv0F9BoQPVVcn5g9Zf4/GfW1w=
